### ISSUE TITLE
Flathub version mismatch

### ISSUE THREAD

**Issue by lriesebos** [flathub/com.notesnook.Notesnook#30]
On flathub, notesnook is still on version 2.x while the [android app](https://f-droid.org/en/packages/com.streetwriters.notesnook/) is already on version 3.x. As a result, the flathub app cannot sync anymore. This is already the case for over a week. Since it seems the 3.x app is still RC, what is the best solution here? Push the RC to flathub to make it usable, or make it at least available through some kind of beta channel (not sure what flathub supports here). Also the web app seems to stick with version 2.x, so using that for a while does not seem to be a solution.
@thecodrr any ideas on how to solve this on the short term?

**Comment by thecodrr** [comment]
You can use the v3 web app here: v3.notesnook.com and download the RC as an AppImage from GitHub: https://github.com/streetwriters/notesnook/releases

**Comment by thecodrr** [comment]
Just pushed v3 beta to flathub. Read more here on how to use `flathub-beta` repo: https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by lriesebos** [comment]
I just wanted to let you know that I moved to the v3 web app on my computer for now, though now the android app runs into issues. The web app still works fine though.

```
Error: Error: [react-native-quick-sqlite] SQL execution error: database disk image is malformed
    at ?anon_0_ (address at index.android.bundle:1:2765977)
    at throw (native)
    at rejected (address at index.android.bundle:1:2764764)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1494525)
    at _callTimer (address at index.android.bundle:1:1493517)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1493686)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1495602)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1391892)
    at anonymous (address at index.android.bundle:1:1391018)
    at __guard (address at index.android.bundle:1:1391769)
    at flushedQueue (address at index.android.bundle:1:1390929)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1390785)
```

**Comment by thecodrr** [comment]
@lriesebos will look into it.
